### Basic Regression

In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [8]:
df1 = pd.read_csv("delta_price_symbols_A_to_D.csv")
df2 = pd.read_csv("delta_price_symbols_E_to_H.csv")
y = pd.read_csv("delta_price_symbol_x.csv")

In [9]:
df1 = df1.drop(['Unnamed: 0'],axis = 1)
df2 = df2.drop(['Unnamed: 0'],axis = 1)
y = y.drop(['Unnamed: 0'],axis = 1)

In [10]:
X = df1.merge(df2, how = 'inner')

In [11]:
X = X.drop('Date',axis = 1)
y = y.drop('Date',axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
#Visualize X to get the order of coef
X

delta_price_A  delta_price_B  delta_price_C  delta_price_D  \
0         0.007782       0.004563       0.007087       0.004751   
1         0.001894       0.001235      -0.000292       0.000728   
2         0.002690       0.007222       0.003319       0.008361   
3         0.007832       0.002739       0.004544      -0.000108   
4        -0.003958      -0.000108       0.001158       0.002956   
..             ...            ...            ...            ...   
120       0.001884       0.000562       0.007068       0.003408   
121      -0.010080      -0.008722      -0.007320      -0.006679   
122       0.009879       0.011064       0.008629       0.016144   
123       0.002107       0.002428       0.001206       0.003364   
124       0.012240       0.023025       0.010050       0.023025   

     delta_price_E  delta_price_F  delta_price_G  delta_price_H  
0         0.013106       0.008679       0.012875       0.009031  
1         0.008951       0.004531       0.005778       0.003098  
2         0.001774       0.004340       0.000402       0.005834  
3         0.004971       0.000227      -0.003388      -0.008132  
4        -0.012963      -0.005968      -0.002132       0.000057  
..             ...            ...            ...            ...  
120       0.018817       0.003656       0.013365       0.007602  
121      -0.014007      -0.006977      -0.000879      -0.007233  
122       0.014772       0.013243       0.010497       0.023114  
123       0.003469       0.005400       0.002613       0.003377  
124       0.016420       0.029600       0.014208       0.032183  

[125 rows x 8 columns]

In [12]:
#Get coefficients
#delta_H is the eighth coef
#it should be 13.76
regressor.coef_

array([[ 14.71527129,  -0.4484446 ,   3.42846403,  -6.53920893,
          0.41411453,  -4.02741014, -15.73961217,  14.14266959]])

In [15]:
pred = regressor.predict(X_test)
mean_squared_error(y_test,pred)

0.00992414997875973

### Ridge Regression and Lasso Regression With Grid Search

In [17]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [21]:
params = {'alpha': [1e-4,1e-2,0.1,1,10]}
lasso = Lasso()
gscv = GridSearchCV(lasso, params)
gscv.fit(X_train,y_train)
gscv.best_params_
gscv.cv_results_

{'mean_fit_time': array([0.00478854, 0.00259399, 0.00220203, 0.00198894, 0.00199471]),
 'std_fit_time': array([1.16905822e-03, 4.88752295e-04, 4.14014559e-04, 1.34544148e-05,
        1.34532318e-06]),
 'mean_score_time': array([0.00299301, 0.00199394, 0.00159416, 0.00159521, 0.00160108]),
 'std_score_time': array([0.00063049, 0.0006306 , 0.00048882, 0.00049092, 0.00049587]),
 'param_alpha': masked_array(data=[0.0001, 0.01, 0.1, 1, 10],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 0.0001},
  {'alpha': 0.01},
  {'alpha': 0.1},
  {'alpha': 1},
  {'alpha': 10}],
 'split0_test_score': array([-0.02548635, -0.06045733, -0.06045733, -0.06045733, -0.06045733]),
 'split1_test_score': array([ 0.15629073, -0.00258469, -0.00258469, -0.00258469, -0.00258469]),
 'split2_test_score': array([-0.09961968, -0.18459404, -0.18459404, -0.18459404, -0.18459404]),
 'split3_test_score': array([ 0.07654946, -0.01248245, -0.0124

In [23]:
lasso = gscv.best_estimator_
lasso.score(X_train, y_train)

0.17849593963319388

### Fit a SVR Regression Model

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [14]:
from sklearn import svm
svr = svm.SVR()
params = {'kernel':['linear','rbf','sigmoid','poly'],'C':[1,2,4,8,10]}
gscv = GridSearchCV(svr,params)

In [15]:
gscv.fit(X_train, y_train)
gscv.best_params_

G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

{'C': 8, 'kernel': 'linear'}

In [16]:
svr = gscv.best_estimator_
pred = svr.predict(X_test)


In [17]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,pred)

0.009922218054472392

### Basic Classification

In [34]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [35]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

In [36]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors = 2)
knn.fit(X_train, y_train)
pred_train = knn.predict(X_train)
print(accuracy_score(y_train, pred_train))
pred_test = knn.predict(X_test)
print(accuracy_score(y_test, pred_test))

0.9642857142857143
0.9736842105263158


In [37]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [10]:
pred_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [38]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred_test))

[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


In [39]:
from sklearn.metrics import classification_report
classification_report(y_test, pred_test)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        15\n           1       0.92      1.00      0.96        11\n           2       1.00      0.92      0.96        12\n\n    accuracy                           0.97        38\n   macro avg       0.97      0.97      0.97        38\nweighted avg       0.98      0.97      0.97        38\n'

### Use Grid Search in Basic Classification Setting

In [40]:
from sklearn.model_selection import GridSearchCV


In [41]:
params = {'n_neighbors':[1,2,3,4,5]}
knn = neighbors.KNeighborsClassifier()
gscv = GridSearchCV(knn,params,scoring = 'accuracy',n_jobs = -1,cv = 10)
gscv.fit(X_train, y_train)
gscv.best_params_

{'n_neighbors': 4}

In [42]:
gscv.best_score_

0.9371212121212121

In [43]:
gscv.cv_results_

{'mean_fit_time': array([0.00099695, 0.00069768, 0.00089984, 0.00059795, 0.00079744]),
 'std_fit_time': array([0.0004458 , 0.00063742, 0.00029998, 0.00048823, 0.00039873]),
 'mean_score_time': array([0.00239441, 0.00279253, 0.00159376, 0.00189567, 0.00219371]),
 'std_score_time': array([0.00101631, 0.0014654 , 0.00048799, 0.00029954, 0.0003988 ]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5}],
 'split0_test_score': array([0.91666667, 0.91666667, 0.91666667, 0.91666667, 0.91666667]),
 'split1_test_score': array([1., 1., 1., 1., 1.]),
 'split2_test_score': array([1.        , 0.90909091, 1.        , 0.90909091, 0.90909091]),
 'split3_test_score': array([1., 1., 1., 1., 1.]),
 'split4_test_score': array([0.72727273, 0.72727273, 0.72727273, 0.81818182, 0.8

In [44]:
knn = gscv.best_estimator_
pred = knn.predict(X_test)
accuracy_score(y_test, pred)

0.9736842105263158

### Use SVM and Grid Search CV

In [6]:
from sklearn import svm
svc = svm.SVC()
params = {'C':[1,2,4,8],'kernel':['linear','rbf']}
clf = GridSearchCV(svc, params)
clf.fit(X_train, y_train)
clf.best_params_

{'C': 8, 'kernel': 'linear'}

In [7]:
svc = clf.best_estimator_
pred = svc.predict(X_test)
accuracy_score(y_test,pred)

0.9736842105263158

### Dimension Reduction: PCA

fit_transform可以直接算出来

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.95)
pca.fit(X)
print(pca.explained_variance_ratio_)

[0.66292517 0.23620961 0.0498649  0.02606215]


In [28]:
X_train = pca.fit_transform(X)
X_train.shape

(125, 4)

In [29]:
lr = LinearRegression()


In [30]:
lr.fit(X_train, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
y_pred = lr.predict(X_train)
mean_squared_error(y,y_pred)

0.01886572157723369

### Different Preprocessing Methods

#### Scalers

**StandardScaler: $(x-\mu)/\sigma$**

In [1]:
from sklearn import datasets, preprocessing

In [11]:
iris = datasets.load_iris()
X, y = iris.data, iris.target

In [13]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X_train = scaler.transform(X)

In [8]:
X_train[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

#### Normalizer: Normalize vectors to have norm 1

In [10]:
from sklearn.preprocessing import Normalizer

In [12]:
transformer = Normalizer().fit(X)
X_train = transformer.transform(X)
X_train

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

#### Binarizer

In [15]:
from sklearn.preprocessing import Binarizer
bi = Binarizer(threshold = 2).fit(X)
X_train = bi.transform(X)
X_train

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],


### Logistic Regression

In [1]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
X, y = datasets.load_iris(return_X_y = True)

In [8]:
clf = LogisticRegression()
#We can use different C
#The logistic regression can be used in multi classes settings, where we assume a 
params = {'C': [1,2,4,8,10]}
gscv = GridSearchCV(clf, params, scoring = 'accuracy')
gscv.fit(X,y)
gscv.cv_results_

G:\Users\72313\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
G:\Users\72313\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

{'mean_fit_time': array([0.02376204, 0.02074447, 0.02513227, 0.02593174, 0.02313619]),
 'std_fit_time': array([0.00652669, 0.0007469 , 0.00203355, 0.00649758, 0.00116632]),
 'mean_score_time': array([0.00019979, 0.        , 0.00039983, 0.00019956, 0.0001997 ]),
 'std_score_time': array([0.00039959, 0.        , 0.00048969, 0.00039911, 0.0003994 ]),
 'param_C': masked_array(data=[1, 2, 4, 8, 10],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1}, {'C': 2}, {'C': 4}, {'C': 8}, {'C': 10}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.97333333, 0.97

In [9]:
clf = gscv.best_estimator_
clf.score(X,y)

0.98

### Tree Based Models

#### Random Forest Classifier

In [12]:
from sklearn.ensemble import RandomForestClassifier 
Rd = RandomForestClassifier()
params = {'n_estimators':[100,200,300],'criterion':['gini','entropy'], 'max_depth' : [5,10,15,20]}
gscv = GridSearchCV(Rd, params, scoring = 'accuracy')
gscv.fit(X,y)
gscv.best_params_

{'criterion': 'gini', 'max_depth': 5, 'n_estimators': 100}

In [17]:
Rd = gscv.best_estimator_
pred = Rd.predict(X)

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y,pred)

1.0

#### LightGBM

In [2]:
import lightgbm as lgb
#Grid Search Parameters
params = {'boosting_type':['gbdt'],'learning_rate':[0.3,0.1,0.01],
         'max_depth':[3,5,7,9],
         'n_estimators':[100,300,500],
         'num_leaves':[20,35,50,75,100],
         'random_state':[42]}
model = lgb.LGBMClassifier()
gscv = GridSearchCV(model, params, scoring = 'accuracy')
gscv.fit(X,y)
gscv.best_params_

{'boosting_type': 'gbdt',
 'learning_rate': 0.3,
 'max_depth': 7,
 'n_estimators': 300,
 'num_leaves': 20,
 'random_state': 42}

In [3]:
model = gscv.best_estimator_
model.score(X,y)

1.0